/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedBudgetsRouteImport } from './routes/_authenticated/budgets'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCommandCenterRouteImport } from './routes/_authenticated/command-center'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDivisionsRouteImport } from './routes/_authenticated/divisions'
import { Route as AuthenticatedFundApprovalsRouteImport } from './routes/_authenticated/fund-approvals'
import { Route as AuthenticatedMemberProgressRouteImport } from './routes/_authenticated/member-progress'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedMentorTasksRouteImport } from './routes/_authenticated/mentor-tasks'
import { Route as AuthenticatedMousRouteImport } from './routes/_authenticated/mous'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies.index'
import { Route as AuthenticatedCompaniesIdRouteImport } from './routes/_authenticated/companies.$id'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events.index'
import { Route as AuthenticatedEventsIdRouteImport } from './routes/_authenticated/events.$id'
import { Route as AuthenticatedFundRequestsIndexRouteImport } from './routes/_authenticated/fund-requests.index'
import { Route as AuthenticatedFundRequestsIdRouteImport } from './routes/_authenticated/fund-requests.$id'
import { Route as AuthenticatedMeetingsIndexRouteImport } from './routes/_authenticated/meetings.index'
import { Route as AuthenticatedMeetingsIdRouteImport } from './routes/_authenticated/meetings.$id'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated/settings.organization'
import { Route as AuthenticatedSpeakersIndexRouteImport } from './routes/_authenticated/speakers.index'
import { Route as AuthenticatedSpeakersIdRouteImport } from './routes/_authenticated/speakers.$id'
import { Route as AuthenticatedMentorAssignmentsIndexRouteImport } from './routes/_authenticated/mentor.assignments.index'
import { Route as AuthenticatedMentorAssignmentsIdRouteImport } from './routes/_authenticated/mentor.assignments.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBudgetsRoute = AuthenticatedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandCenterRoute =
  AuthenticatedCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDivisionsRoute = AuthenticatedDivisionsRouteImport.update({
  id: '/divisions',
  path: '/divisions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFundApprovalsRoute =
  AuthenticatedFundApprovalsRouteImport.update({
    id: '/fund-approvals',
    path: '/fund-approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMemberProgressRoute =
  AuthenticatedMemberProgressRouteImport.update({
    id: '/member-progress',
    path: '/member-progress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorTasksRoute =
  AuthenticatedMentorTasksRouteImport.update({
    id: '/mentor-tasks',
    path: '/mentor-tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMousRoute = AuthenticatedMousRouteImport.update({
  id: '/mous',
  path: '/mous',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/admin/categories',
    path: '/admin/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesIdRoute =
  AuthenticatedCompaniesIdRouteImport.update({
    id: '/companies/$id',
    path: '/companies/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIdRoute = AuthenticatedEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFundRequestsIndexRoute =
  AuthenticatedFundRequestsIndexRouteImport.update({
    id: '/fund-requests/',
    path: '/fund-requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundRequestsIdRoute =
  AuthenticatedFundRequestsIdRouteImport.update({
    id: '/fund-requests/$id',
    path: '/fund-requests/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetingsIndexRoute =
  AuthenticatedMeetingsIndexRouteImport.update({
    id: '/meetings/',
    path: '/meetings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetingsIdRoute = AuthenticatedMeetingsIdRouteImport.update({
  id: '/meetings/$id',
  path: '/meetings/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSpeakersIndexRoute =
  AuthenticatedSpeakersIndexRouteImport.update({
    id: '/speakers/',
    path: '/speakers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSpeakersIdRoute = AuthenticatedSpeakersIdRouteImport.update({
  id: '/speakers/$id',
  path: '/speakers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorAssignmentsIndexRoute =
  AuthenticatedMentorAssignmentsIndexRouteImport.update({
    id: '/mentor/assignments/',
    path: '/mentor/assignments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorAssignmentsIdRoute =
  AuthenticatedMentorAssignmentsIdRouteImport.update({
    id: '/mentor/assignments/$id',
    path: '/mentor/assignments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/divisions': typeof AuthenticatedDivisionsRoute
  '/fund-approvals': typeof AuthenticatedFundApprovalsRoute
  '/member-progress': typeof AuthenticatedMemberProgressRoute
  '/members': typeof AuthenticatedMembersRoute
  '/mentor-tasks': typeof AuthenticatedMentorTasksRoute
  '/mous': typeof AuthenticatedMousRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/events/$id': typeof AuthenticatedEventsIdRoute
  '/fund-requests/$id': typeof AuthenticatedFundRequestsIdRoute
  '/meetings/$id': typeof AuthenticatedMeetingsIdRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/speakers/$id': typeof AuthenticatedSpeakersIdRoute
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/fund-requests/': typeof AuthenticatedFundRequestsIndexRoute
  '/meetings/': typeof AuthenticatedMeetingsIndexRoute
  '/speakers/': typeof AuthenticatedSpeakersIndexRoute
  '/mentor/assignments/$id': typeof AuthenticatedMentorAssignmentsIdRoute
  '/mentor/assignments/': typeof AuthenticatedMentorAssignmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/divisions': typeof AuthenticatedDivisionsRoute
  '/fund-approvals': typeof AuthenticatedFundApprovalsRoute
  '/member-progress': typeof AuthenticatedMemberProgressRoute
  '/members': typeof AuthenticatedMembersRoute
  '/mentor-tasks': typeof AuthenticatedMentorTasksRoute
  '/mous': typeof AuthenticatedMousRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/events/$id': typeof AuthenticatedEventsIdRoute
  '/fund-requests/$id': typeof AuthenticatedFundRequestsIdRoute
  '/meetings/$id': typeof AuthenticatedMeetingsIdRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/speakers/$id': typeof AuthenticatedSpeakersIdRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/fund-requests': typeof AuthenticatedFundRequestsIndexRoute
  '/meetings': typeof AuthenticatedMeetingsIndexRoute
  '/speakers': typeof AuthenticatedSpeakersIndexRoute
  '/mentor/assignments/$id': typeof AuthenticatedMentorAssignmentsIdRoute
  '/mentor/assignments': typeof AuthenticatedMentorAssignmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/budgets': typeof AuthenticatedBudgetsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/divisions': typeof AuthenticatedDivisionsRoute
  '/_authenticated/fund-approvals': typeof AuthenticatedFundApprovalsRoute
  '/_authenticated/member-progress': typeof AuthenticatedMemberProgressRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/mentor-tasks': typeof AuthenticatedMentorTasksRoute
  '/_authenticated/mous': typeof AuthenticatedMousRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/_authenticated/events/$id': typeof AuthenticatedEventsIdRoute
  '/_authenticated/fund-requests/$id': typeof AuthenticatedFundRequestsIdRoute
  '/_authenticated/meetings/$id': typeof AuthenticatedMeetingsIdRoute
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/_authenticated/speakers/$id': typeof AuthenticatedSpeakersIdRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/fund-requests/': typeof AuthenticatedFundRequestsIndexRoute
  '/_authenticated/meetings/': typeof AuthenticatedMeetingsIndexRoute
  '/_authenticated/speakers/': typeof AuthenticatedSpeakersIndexRoute
  '/_authenticated/mentor/assignments/$id': typeof AuthenticatedMentorAssignmentsIdRoute
  '/_authenticated/mentor/assignments/': typeof AuthenticatedMentorAssignmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/announcements'
    | '/budgets'
    | '/calendar'
    | '/command-center'
    | '/dashboard'
    | '/divisions'
    | '/fund-approvals'
    | '/member-progress'
    | '/members'
    | '/mentor-tasks'
    | '/mous'
    | '/pipeline'
    | '/profile'
    | '/transactions'
    | '/workspace'
    | '/admin/categories'
    | '/companies/$id'
    | '/events/$id'
    | '/fund-requests/$id'
    | '/meetings/$id'
    | '/settings/organization'
    | '/speakers/$id'
    | '/companies/'
    | '/events/'
    | '/fund-requests/'
    | '/meetings/'
    | '/speakers/'
    | '/mentor/assignments/$id'
    | '/mentor/assignments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/announcements'
    | '/budgets'
    | '/calendar'
    | '/command-center'
    | '/dashboard'
    | '/divisions'
    | '/fund-approvals'
    | '/member-progress'
    | '/members'
    | '/mentor-tasks'
    | '/mous'
    | '/pipeline'
    | '/profile'
    | '/transactions'
    | '/workspace'
    | '/admin/categories'
    | '/companies/$id'
    | '/events/$id'
    | '/fund-requests/$id'
    | '/meetings/$id'
    | '/settings/organization'
    | '/speakers/$id'
    | '/companies'
    | '/events'
    | '/fund-requests'
    | '/meetings'
    | '/speakers'
    | '/mentor/assignments/$id'
    | '/mentor/assignments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/announcements'
    | '/_authenticated/budgets'
    | '/_authenticated/calendar'
    | '/_authenticated/command-center'
    | '/_authenticated/dashboard'
    | '/_authenticated/divisions'
    | '/_authenticated/fund-approvals'
    | '/_authenticated/member-progress'
    | '/_authenticated/members'
    | '/_authenticated/mentor-tasks'
    | '/_authenticated/mous'
    | '/_authenticated/pipeline'
    | '/_authenticated/profile'
    | '/_authenticated/transactions'
    | '/_authenticated/workspace'
    | '/_authenticated/admin/categories'
    | '/_authenticated/companies/$id'
    | '/_authenticated/events/$id'
    | '/_authenticated/fund-requests/$id'
    | '/_authenticated/meetings/$id'
    | '/_authenticated/settings/organization'
    | '/_authenticated/speakers/$id'
    | '/_authenticated/companies/'
    | '/_authenticated/events/'
    | '/_authenticated/fund-requests/'
    | '/_authenticated/meetings/'
    | '/_authenticated/speakers/'
    | '/_authenticated/mentor/assignments/$id'
    | '/_authenticated/mentor/assignments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budgets': {
      id: '/_authenticated/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthenticatedBudgetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/divisions': {
      id: '/_authenticated/divisions'
      path: '/divisions'
      fullPath: '/divisions'
      preLoaderRoute: typeof AuthenticatedDivisionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund-approvals': {
      id: '/_authenticated/fund-approvals'
      path: '/fund-approvals'
      fullPath: '/fund-approvals'
      preLoaderRoute: typeof AuthenticatedFundApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/member-progress': {
      id: '/_authenticated/member-progress'
      path: '/member-progress'
      fullPath: '/member-progress'
      preLoaderRoute: typeof AuthenticatedMemberProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor-tasks': {
      id: '/_authenticated/mentor-tasks'
      path: '/mentor-tasks'
      fullPath: '/mentor-tasks'
      preLoaderRoute: typeof AuthenticatedMentorTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mous': {
      id: '/_authenticated/mous'
      path: '/mous'
      fullPath: '/mous'
      preLoaderRoute: typeof AuthenticatedMousRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/$id': {
      id: '/_authenticated/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AuthenticatedCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$id': {
      id: '/_authenticated/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof AuthenticatedEventsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund-requests/': {
      id: '/_authenticated/fund-requests/'
      path: '/fund-requests'
      fullPath: '/fund-requests/'
      preLoaderRoute: typeof AuthenticatedFundRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund-requests/$id': {
      id: '/_authenticated/fund-requests/$id'
      path: '/fund-requests/$id'
      fullPath: '/fund-requests/$id'
      preLoaderRoute: typeof AuthenticatedFundRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings/': {
      id: '/_authenticated/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof AuthenticatedMeetingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings/$id': {
      id: '/_authenticated/meetings/$id'
      path: '/meetings/$id'
      fullPath: '/meetings/$id'
      preLoaderRoute: typeof AuthenticatedMeetingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/speakers/': {
      id: '/_authenticated/speakers/'
      path: '/speakers'
      fullPath: '/speakers/'
      preLoaderRoute: typeof AuthenticatedSpeakersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/speakers/$id': {
      id: '/_authenticated/speakers/$id'
      path: '/speakers/$id'
      fullPath: '/speakers/$id'
      preLoaderRoute: typeof AuthenticatedSpeakersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/assignments/': {
      id: '/_authenticated/mentor/assignments/'
      path: '/mentor/assignments'
      fullPath: '/mentor/assignments/'
      preLoaderRoute: typeof AuthenticatedMentorAssignmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/assignments/$id': {
      id: '/_authenticated/mentor/assignments/$id'
      path: '/mentor/assignments/$id'
      fullPath: '/mentor/assignments/$id'
      preLoaderRoute: typeof AuthenticatedMentorAssignmentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedBudgetsRoute: typeof AuthenticatedBudgetsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCommandCenterRoute: typeof AuthenticatedCommandCenterRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDivisionsRoute: typeof AuthenticatedDivisionsRoute
  AuthenticatedFundApprovalsRoute: typeof AuthenticatedFundApprovalsRoute
  AuthenticatedMemberProgressRoute: typeof AuthenticatedMemberProgressRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedMentorTasksRoute: typeof AuthenticatedMentorTasksRoute
  AuthenticatedMousRoute: typeof AuthenticatedMousRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedCompaniesIdRoute: typeof AuthenticatedCompaniesIdRoute
  AuthenticatedEventsIdRoute: typeof AuthenticatedEventsIdRoute
  AuthenticatedFundRequestsIdRoute: typeof AuthenticatedFundRequestsIdRoute
  AuthenticatedMeetingsIdRoute: typeof AuthenticatedMeetingsIdRoute
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
  AuthenticatedSpeakersIdRoute: typeof AuthenticatedSpeakersIdRoute
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedFundRequestsIndexRoute: typeof AuthenticatedFundRequestsIndexRoute
  AuthenticatedMeetingsIndexRoute: typeof AuthenticatedMeetingsIndexRoute
  AuthenticatedSpeakersIndexRoute: typeof AuthenticatedSpeakersIndexRoute
  AuthenticatedMentorAssignmentsIdRoute: typeof AuthenticatedMentorAssignmentsIdRoute
  AuthenticatedMentorAssignmentsIndexRoute: typeof AuthenticatedMentorAssignmentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedBudgetsRoute: AuthenticatedBudgetsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCommandCenterRoute: AuthenticatedCommandCenterRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDivisionsRoute: AuthenticatedDivisionsRoute,
  AuthenticatedFundApprovalsRoute: AuthenticatedFundApprovalsRoute,
  AuthenticatedMemberProgressRoute: AuthenticatedMemberProgressRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedMentorTasksRoute: AuthenticatedMentorTasksRoute,
  AuthenticatedMousRoute: AuthenticatedMousRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedCompaniesIdRoute: AuthenticatedCompaniesIdRoute,
  AuthenticatedEventsIdRoute: AuthenticatedEventsIdRoute,
  AuthenticatedFundRequestsIdRoute: AuthenticatedFundRequestsIdRoute,
  AuthenticatedMeetingsIdRoute: AuthenticatedMeetingsIdRoute,
  AuthenticatedSettingsOrganizationRoute:
    AuthenticatedSettingsOrganizationRoute,
  AuthenticatedSpeakersIdRoute: AuthenticatedSpeakersIdRoute,
  AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedFundRequestsIndexRoute: AuthenticatedFundRequestsIndexRoute,
  AuthenticatedMeetingsIndexRoute: AuthenticatedMeetingsIndexRoute,
  AuthenticatedSpeakersIndexRoute: AuthenticatedSpeakersIndexRoute,
  AuthenticatedMentorAssignmentsIdRoute: AuthenticatedMentorAssignmentsIdRoute,
  AuthenticatedMentorAssignmentsIndexRoute:
    AuthenticatedMentorAssignmentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
